post: ng v11
Ninja-Squad/ninja-squad.github.com pull request #323
Opened 2020-10-30 11:09 UTC by cexbrayat

2020-10-31 07:37 UTC, jnizet requested changes

2020-10-31 07:37 UTC, jnizet commented on _posts/2020-11-11-angular-cli-11.0.md
> +This is part of the effort to support Trusted types in Angular,
If you have a link explaining what trusted types and these headers are for, that would be nice here.

2020-10-31 07:37 UTC, jnizet commented on _posts/2020-11-11-angular-cli-11.0.md
> +so you probably don't have them anymore.
Some other options previously deprecated have been removed,.
You probably don't use them anymore, but if you still do, the migration schematic will replace them with the proper alternative.

2020-10-31 07:37 UTC, jnizet commented on _posts/2020-11-11-angular-cli-11.0.md
> +Not that the `--lint-fix` flag the `generate` command offered has been deprecated:
Note that the `--lint-fix` flag of the `generate` command has been deprecated:

2020-10-31 07:37 UTC, jnizet commented on _posts/2020-11-11-what-is-new-angular-11.0.md
> +As often, the Angular team already wrote a migration for us.
Don't you only have to deal with it if the "strict null checks" Typescript option is on?

2020-10-31 07:37 UTC, jnizet commented on _posts/2020-11-11-what-is-new-angular-11.0.md
> +The legacy method is also not very good at handling spaces in ICUs expressions for example.
ICU expressions

2020-10-31 07:37 UTC, jnizet commented
Great posts! 👏

2020-11-02 16:18 UTC, cexbrayat commented on _posts/2020-11-11-what-is-new-angular-11.0.md
> +As often, the Angular team already wrote a migration for us.
Yeah probably 👍

2020-11-12 08:03 UTC, merged