post: ng v11.1
Ninja-Squad/ninja-squad.github.com pull request #325
Opened 2021-01-06 11:09 UTC by cexbrayat

TODO:
- [ ] changelog link

2021-01-15 08:50 UTC, jnizet requested changes

2021-01-15 08:50 UTC, jnizet commented on _posts/2021-01-13-angular-cli-11.1.md
> +    Support for camel case arguments has been deprecated and will be removed in a future major version.
camel case or camel cased? I think I prefer the first one, but we should be consistent.

2021-01-15 08:50 UTC, jnizet commented on _posts/2021-01-13-angular-cli-11.1.md
> +    }
So, in those formats, the meaning and description we might have in the source files for each key are ignored?

2021-01-15 08:50 UTC, jnizet commented on _posts/2021-01-13-what-is-new-angular-11.1.md
> +You can now use `elements.get(1)` (same as `element[1]`).
Is that correct? Didn't we have to do `elements.toArray()[index]`? See https://github.com/angular/angular/issues/29467: the point, AFAIU, is precisely to avoid having to make a copy of the whole array just to get an element at a given index.

2021-01-15 08:50 UTC, jnizet commented on _posts/2021-01-13-what-is-new-angular-11.1.md
> +If you give no value to this input, the `routerLink` is resolved relatively to the root (as it is by default).
I don't think that is true. We frequently use `[routerLink]="['edit']`, and the link is relative to the current route, not to root.

2021-01-15 09:00 UTC, cexbrayat commented on _posts/2021-01-13-angular-cli-11.1.md
> +    Support for camel case arguments has been deprecated and will be removed in a future major version.
I'll use came case everywhere 👍

2021-01-15 09:00 UTC, cexbrayat commented on _posts/2021-01-13-angular-cli-11.1.md
> +    }
That's right (as far as I can see). I'll add a note as it's an important difference.

2021-01-15 09:01 UTC, cexbrayat commented on _posts/2021-01-13-what-is-new-angular-11.1.md
> +You can now use `elements.get(1)` (same as `element[1]`).
Oh, I misread the commit, you're right! I'll change to mention `toArray`

2021-01-15 09:03 UTC, cexbrayat commented on _posts/2021-01-13-what-is-new-angular-11.1.md
> +If you give no value to this input, the `routerLink` is resolved relatively to the root (as it is by default).
I think my brain crashed between route and root. Yeah, this is relatevely to the (current) route, I'll fix 👍

2021-01-15 09:09 UTC, cexbrayat commented on _posts/2021-01-13-angular-cli-11.1.md
> +    }
I checked again, and in fact ARB is keeping these informations: they are just ignored in the JSON format

2021-01-21 07:27 UTC, jnizet requested changes

2021-01-21 07:27 UTC, jnizet commented on _posts/2021-01-21-angular-cli-11.1.md
> +Karma has released a [new 6.0 version](https://github.com/karma-runner/karma/releases/tag/v6.0.0).
FYI: they have released a 6.0.1 version, that is compatible again with previous versions of the CLI.

2021-01-21 07:27 UTC, jnizet commented on _posts/2021-01-21-what-is-new-angular-11.1.md
> +and add some really nice features at the same time!
and added

2021-01-21 07:27 UTC, jnizet commented on _posts/2021-01-21-what-is-new-angular-11.1.md
> +If you want to learn more about what is the Language Service,
about the Language Service

2021-01-21 07:27 UTC, jnizet commented on _posts/2021-01-21-what-is-new-angular-11.1.md
> +and what's new with this new version,
and about the new features of this version

2021-01-21 08:38 UTC, merged