post: ng and cli v15.1
Ninja-Squad/ninja-squad.github.com pull request #364
Opened 2022-12-15 20:17 UTC by cexbrayat

2023-01-05 09:56 UTC, jnizet requested changes

2023-01-05 09:56 UTC, jnizet commented on _posts/2023-01-09-what-is-new-angular-15.1.md
> +This release is packed with features as you can see,
I wouldn't say it's packed with features, no.

2023-01-06 08:01 UTC, cexbrayat commented on _posts/2023-01-09-what-is-new-angular-15.1.md
> +    this.router.navigateByUrl('/user', { onSameUrlNavigation: 'reload' })
IIRC it recreates the component if you combine that with a reuse strategy

2023-01-06 08:03 UTC, cexbrayat commented on _posts/2023-01-09-angular-cli-15.1.md
> +to generate the `.browserslistrc` file.
Nope ^^

2023-01-06 08:03 UTC, cexbrayat commented on _posts/2023-01-09-angular-cli-15.1.md
> +It now supports Sass inline styles. Less is not supported yet.
When it's directly in the component decorator?

2023-01-06 08:03 UTC, cexbrayat commented on _posts/2023-01-09-what-is-new-angular-15.1.md
> +This release is packed with features as you can see,
Good catch, it's a leftover my previous blog post

2023-01-11 15:57 UTC, merged