post: how to migrate to standalone components
Ninja-Squad/ninja-squad.github.com pull request #365
Opened 2023-02-06 16:55 UTC by cexbrayat

2023-02-06 20:53 UTC, jnizet requested changes

2023-02-06 20:53 UTC, jnizet commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +Angular&nbsp;14 introduced standalone components et optional modules.
et -> and

2023-02-06 20:53 UTC, jnizet commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +except the ones referenced in your main module.
"referenced" is a bit vague here. Does it mean "declared"? "bootstrapped"?

2023-02-06 20:53 UTC, jnizet commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +The schematic is quite smart, as it compiles the template of each component to detect what the standalone version of the component needs to import.
That makes me think that a nice (and probably much simpler) schematic that would be nice to have would be one that would analyze the imports of a standalone component, and remove the ones that are not necessary: AFAIK, there's nothing that tells you that an imported component, pipe or directive isn't actually used inside the template

2023-02-06 20:53 UTC, jnizet commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +because the schematics sometimes reformat the code.
reformat -> reformats

2023-02-06 20:53 UTC, jnizet commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +as well as the migrated pipes and directives.
The wording is a bit strange: pipes can't be standalone components.

2023-02-06 20:53 UTC, jnizet commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +If you module has providers, you can usually move them.
you -> your

2023-02-07 07:24 UTC, cexbrayat commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +The schematic is quite smart, as it compiles the template of each component to detect what the standalone version of the component needs to import.
Exactly, I hope this will be implemented

2023-02-20 15:09 UTC, jnizet requested changes

2023-02-20 15:09 UTC, jnizet commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +because the schematics sometimes reformats the code.
schematics -> schematic

2023-02-20 15:09 UTC, jnizet commented on _posts/2023-02-15-migrate-an-angular-application-to-standalone.md
> +This last one means that modules that imports a module with providers
imports -> import

2023-02-21 09:40 UTC, merged