post: ng and cli v15.2
Ninja-Squad/ninja-squad.github.com pull request #366
Opened 2023-02-11 14:15 UTC by cexbrayat

2023-02-20 15:30 UTC, jnizet requested changes

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +The Angular team has been working on a different way to handle state and changes in your application for the past year.
I'd change "state and changes" to "reactivity"

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +and to allow the framework to only re-render the parts of your application that are impacted by a change.
I'd rephrase as "and to allow the framework to know which components are impacted by a change, rather than having to detect changes on the whole tree of components."

because Angular *already* re-renders only the parts that are impacted by a change. But it has to detect the changes everywhere.

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +This would be a significative change to how Angular works, as it currently relies on zone.js to detect changes and re-render the whole tree of components by default.
I'd rephrase as "to detect changes in the whole tree of components by default".

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +Instead, with signals, the framework would only re-render the components that are impacted by a change.
> would know which components are impacted, without needing to check all the other ones. 

This also opens the door to zoneless applications, i.e. applications where Angular applications don't need to include Zone.js (which makes them lighter), and don't have to patch all the browser APIs (which makes them start faster).

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +    count.mutate((user) => user.name = 'Cédric');
weird to use the same `count` signal here.

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +Once you have define signals, you define computed values that derive from them:
define -> defined
you define -> you can define

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +    effect(() => console.log(count()));
Are you sure about that? See https://github.com/angular/angular/pull/49091#pullrequestreview-1300300096.

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +
I would maybe add that, despite looking like a BehaviorSubject, it has some subtle differences, the most important one being that unsubscribing is unnecessary thanks to the usage of weak references.

2023-02-20 15:30 UTC, jnizet commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +The framework would then only re-render the component when one of the signals it depends on changes,
would be notified when an expression has changed thanks to the signals, and would thus only need to re-render the components affected by the change, without having to check for changes on unrelated components, without the need for zone.js

2023-02-21 14:35 UTC, cexbrayat commented on _posts/2023-02-22-what-is-new-angular-15.2.md
> +    effect(() => console.log(count()));
Yeah, it's not exposed publicly in the current PR, but I suppose there will be something similar in the end as effects/watcher are a necessary part. Maybe this name and others will change as well as the PR is not merged, but it's just to give an idea of it will look like

2023-02-23 08:46 UTC, merged