post: ng and cli v16
Ninja-Squad/ninja-squad.github.com pull request #373
Opened 2023-04-29 10:10 UTC by cexbrayat

2023-04-30 16:11 UTC, jnizet requested changes

2023-04-30 16:11 UTC, jnizet commented on _posts/2023-05-03-angular-cli-16.0.md
> +and add the concept of modules only matter, when it makes sense!
> and add the concept of modules only matter, when it makes sense!

I don't understand precisely what you meant here. Needs to be rephrased.

2023-04-30 16:11 UTC, jnizet commented on _posts/2023-05-03-angular-cli-16.0.md
> +[Web Test Runner](https://modern-web.dev/docs/test-runner/overview/),
Unrelated to the review, but I'm looking forward to this much more than Jest.

2023-04-30 16:11 UTC, jnizet commented on _posts/2023-05-03-what-is-new-angular-16.0.md
> +This has been a long-awaited feature, we're happy to this land in Angular!
to **see** this land

2023-04-30 16:11 UTC, jnizet commented on _posts/2023-05-03-what-is-new-angular-16.0.md
> +If some parts of your templates will not produce the same result on the server and the client, you can skip them by adding `ngSkipHydration` to the element or component.
will not -> don't

2023-04-30 16:11 UTC, jnizet commented on _posts/2023-05-03-what-is-new-angular-16.0.md
> +i18n is also not yet supported, but that should come soon.
not supported yet

2023-04-30 16:11 UTC, jnizet commented on _posts/2023-05-03-what-is-new-angular-16.0.md
> +    { provide: REMOVE_STYLES_ON_COMPONENT_DESTROY, useValue: true }
I didn't even know this wasn't the case already. So they add them to the styles on first use, and leave them there forever?

2023-04-30 16:11 UTC, jnizet commented on _posts/2023-05-03-what-is-new-angular-16.0.md
> +With this option, a component can declare an input with the same name as a route parameter or data, and Angular will automatically bind the value of the parameter or data to this input.
Might be nice to say if this also supports query parameters.

2023-05-01 00:24 UTC, cexbrayat commented on _posts/2023-05-03-angular-cli-16.0.md
> +[Web Test Runner](https://modern-web.dev/docs/test-runner/overview/),
Hihi I suspected so 😉

2023-05-01 00:25 UTC, cexbrayat commented on _posts/2023-05-03-what-is-new-angular-16.0.md
> +    { provide: REMOVE_STYLES_ON_COMPONENT_DESTROY, useValue: true }
Yep

2023-05-04 01:25 UTC, merged