post: ng v18
Ninja-Squad/ninja-squad.github.com pull request #388
Opened 2024-05-16 15:09 UTC by cexbrayat

TODO:
- [ ] CLI article link

2024-05-16 19:28 UTC, jnizet requested changes

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +It should work out of the box if all your components are `OnPush` and/or use signals! 🚀
and/or rely on signal

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +but it's a nice step forward towards a zoneless Angular.
In particular, if you use a component library that isn't ready for zoneless support, you'll have to wait until it is.

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +getTestBed().initTestEnvironment(
I'm not sure I understand where this code would have to be put. Is it in the test.ts file that is no longer generated in new projects?

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +uses the "auto detect changes" strategy by default.
Aaah, so you don't need to call `fixture.autoDetectChanges(true)` when using `provideExperimentalZonelessChangeDetection()` in the tests. 
And I guess you can't use fakeAsync then, since it relies on ZoneJS.

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +  { provide: ComponentFixtureAutoDetect, useValue: true }
I'm confused again. You said before that it was done by default, so why do we need to do that?

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +or by calling `fixture.autoDetectChanges()` in your test.
`fixture.autoDetectChanges(true)`

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +We're probably going to update our ebook and the tests we provide in our online training to use this strategy.
Hmm, but we use ng-bootstrap, and ng-bootstrap is not zoneless-ready. Maybe what we use of ng-bootstrap is, but there are places in the code where it relies on ZoneJS (onStable, IIRC).

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +If you need to fake time in your tests, you can use the `jasmine.clock` APIs instead.
But will that, for example, call the functions passed to setTimeout or setInterval? I doubt it (see https://github.com/angular/angular/issues/55295)

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +The `AbstractControl` (the base class for form controls, groups, arrays, and records) now has a new field called `events`.
field -> property

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +This field is an observable that emits events when the control's value, status, pristine state, or touched state changes.
Doesn't it also emit submitted/reset changes (for the top-level form group)?

edit: yes it does, based on the example below

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +(here the login control, or the form itself for form reset and submission events).
Do you mean that submit events are emitted for every control of the submitted form? Or do you mean that the source is always going to be a form group for those events, but that only that form group's events observable emits the submit event?

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +The `RedirectFunction` introduced allows us to access part of the `ActivatedRouteSnapshot` to build the redirect URL.
The `RedirectFunction` introduced -> The `RedirectFunction` introduced in v18, or The new `RedirectFunction`

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +for example [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) to work with locale dates.
Isn't there an opt-in or an opt-out?

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +for example [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) to work with locale dates.
It would be worth mentioning that this means that we don't need to provide one or several locale data anymore, which will reduce the bundle size.

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +which job is to replay events that happened during the hydration phase.
which job -> whose job?

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +It does know which events, as Angular collected them when rendering the page on the server.
I don't understand this part. How could the server know which events a user has triggered in the browser?

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +and others that are double-clicked, Angular will add listeners for these events:
Do you mean elements which have a `(click)` or a `(doubleclick)` handler?

2024-05-16 19:28 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +It also adds an attribute like `jsaction="click:"` on each HTML element that needs to be listened to.
I think this whole section goes too much into details, and could be removed.

2024-05-17 06:49 UTC, cexbrayat commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +However, the goal is to progressively move away from ZoneJS and rely only on this new scheduler.
Yes, exactly, I explained below

2024-05-17 06:51 UTC, cexbrayat commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +  { provide: ComponentFixtureAutoDetect, useValue: true }
I was showcasing how to enable it in current applications. I'll rephrase.

2024-05-17 06:52 UTC, cexbrayat commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +or by calling `fixture.autoDetectChanges()` in your test.
You don't need to pass `true` it is the default value

2024-05-17 06:53 UTC, cexbrayat commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +We're probably going to update our ebook and the tests we provide in our online training to use this strategy.
Yes I'm not sure everything can work right now, but I plan to move most of them

2024-05-17 07:05 UTC, cexbrayat commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +If you need to fake time in your tests, you can use the `jasmine.clock` APIs instead.
I think it properly works with jasmine and a real browser. At least I was able to use it on a simple setTimeout, and in all the ponyracer tests that use `fakeAsync`

The issue you link talks about a lot of different things, but the fake timers story boils down to where the test is executed. As we're using a real browser, I think we're fine.

2024-05-17 07:11 UTC, cexbrayat commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +It does know which events, as Angular collected them when rendering the page on the server.
I'll rephrase: the compiler collects the events on the server when the HTML is generated.
It doesn't which events a user triggered, but it knows the _potential_ events that can be triggered

2024-05-17 08:41 UTC, cexbrayat commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +(here the login control, or the form itself for form reset and submission events).
I meant that the source is the control or group that became dirty/invalid/changed etc, except the submit and reset one, where the source is the form itself

2024-05-17 11:33 UTC, jnizet requested changes

2024-05-17 11:33 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +With this new scheduler, the framework no longer only rely on ZoneJS to trigger change detection.
rely -> relies

2024-05-17 11:33 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +for example [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) to work with locale dates.
Ah, I get it now. I read too fast and thought they had already merged this PR: https://github.com/angular/angular/pull/55283. But it's apparently for 18.1.

2024-05-19 12:02 UTC, jnizet requested changes

2024-05-19 12:02 UTC, jnizet commented on _posts/2024-05-22-what-is-new-angular-18.0.md
> +We should also see a new feature to declare variables in the template itself, using `@let`.
As well as an option to switch to Intl-based internationalization

2024-05-22 20:20 UTC, merged