post: vue v3.5
Ninja-Squad/ninja-squad.github.com pull request #389
Opened 2024-06-26 13:36 UTC by cexbrayat

TODO:
- [ ] release URL

2024-06-27 07:28 UTC, jnizet requested changes

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +some coming with new features.
OOC: Vue doesn't respect semver?

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +You can disable this feature by setting `propsDestructure: false` in the compiler options,
You can -> You can however

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +You can read more about this feature in the [RFC](https://github.com/vuejs/rfcs/discussions/502).
You can read more -> Read more 

(to avoid the "You can" repetition)

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +It is now possible to specify the possible modifiers for a directive in the type definition:
the possible modifiers -> the allowed modifiers

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +```
I *think* I have understood, but I also think it would be clearer if the example was more concrete, with an effect that does something useful and a cleanup that does something useful.

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +thus allowing to animate the apparition and the disappearance of an element in a different place in the DOM. This used to throw an error in Vue 3.4.
apparition -> appearance

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +We also have a new warning when a `computed` is self-triggering (i.e. it depends on itself):
The 'i.e. depends on itself' seems a bit misleading. I read it as "a computed that would read itself". But the warning seems to say that the problem is that a computed actually writes to some of its dependencies. Something like this in Angular syntax:
```
const firstName = signal('JB');
const lastName = signal'Nizet');
const fullName = computed(() => {
  const result = firstName() + ' ' + lastName();
  if (result.length > 5) {
    lastName.set('...');
  }
  return result;
}
```

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +This brings a few performance improvements (most notably around memory used) and should make the reactivity system more predictable (computed values should now never be stale).
memory used -> memory usage

2024-06-27 07:28 UTC, jnizet commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> + { id: string }
It would be more logical to use `/users/:id` as the path.
And I don't understand why we have both `{ id: string | number }` and `{ id: string }`.

2024-06-28 13:28 UTC, cexbrayat commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +some coming with new features.
It generally does https://vuejs.org/about/releases.html but sometimes small features are included in patches 🤷

2024-06-28 14:00 UTC, cexbrayat commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> +```
I updated the example, let me know if it better

Before
```ts
// starts an interval, called in the watchEffect below
function startInterval(intervalTime, onCleanup) {
  const id = window.setInterval(() => console.log('hello'), intervalTime)
  // we use onCleanup here to clear the interval
  onCleanup(() => window.clearInterval(id));
}

const intervalTime = ref(1000);
watchEffect((onCleanup) => {
  console.log('Interval time changed', intervalTime.value);
  // we need to pass onCleanup to startInterval
  startInterval(intervalTime.value, onCleanup);
});
```

Now
```ts
function startInterval(intervalTime) {
  const id = window.setInterval(() => console.log('hello'), intervalTime)
  //👇 we can now use onEffectCleanup
  onEffectCleanup(() => window.clearInterval(id));
}

const intervalTime = ref(1000);
watchEffect(() => {
  console.log('Interval time changed', intervalTime.value);
  //👇 no need to pass onCleanup anymore
  startInterval(intervalTime.value);
});
```

2024-06-28 14:05 UTC, cexbrayat commented on _posts/2024-07-03-what-is-new-vue-3.5.md
> + { id: string }
the first one is the "raw parameter". it allows building a route with a string or a number. For example `<RouterLink :to="{ name: 'users', params: { id: user.id } }">User</RouterLink>` compiles if user.id is a string or a number.

The second one is the type param you get with useRoute (the activated route in Angular lingo): in that case you get a string (as it the value in the URL)

2024-08-10 15:45 UTC, jnizet approved these changes

2024-09-05 07:23 UTC, merged