post: ng v18.1
Ninja-Squad/ninja-squad.github.com pull request #390
Opened 2024-06-29 17:33 UTC by cexbrayat

2024-07-04 06:11 UTC, jnizet commented on _posts/2024-07-10-what-is-new-angular-18.1.md
> +NG_BUILD_OPTIMIZE_CHUNKS=1 ng build
OOC, do you have the PR / issue where this has been done/discussed? Is it possiblie to configure an option so that we can just do `ng build`?

2024-07-08 18:32 UTC, cexbrayat commented on _posts/2024-07-10-what-is-new-angular-18.1.md
> +You can specify a different host or port if needed with `ng serve --inspect localhost:9999` for example.
It's not available for ng build AFAIK

2024-07-08 18:34 UTC, cexbrayat commented on _posts/2024-07-10-what-is-new-angular-18.1.md
> +NG_BUILD_OPTIMIZE_CHUNKS=1 ng build
Right now it's not possible otherwise, but it'll become the default soon I suppose

2024-07-08 18:34 UTC, cexbrayat commented on _posts/2024-07-10-what-is-new-angular-18.1.md
> +NG_BUILD_OPTIMIZE_CHUNKS=1 ng build
https://github.com/angular/angular-cli/commit/a5f1b918fdbc64b8007fd329e014fe1b16260cb3

2024-07-08 18:43 UTC, cexbrayat commented
@jnizet I pushed a fixup commit with fixes and some new stuff if you can take a look when you have some time

2024-07-10 08:38 UTC, jnizet requested changes

2024-07-10 08:38 UTC, jnizet commented on _posts/2024-07-10-what-is-new-angular-18.1.md
> +The `phase` parameter is now deprecated: we now pass to these functions an object instead of a callback, to specify the phase you want to use.
the phase  -> the phases

2024-07-10 08:38 UTC, jnizet commented on _posts/2024-07-10-what-is-new-angular-18.1.md
> +so you safely add it to your own projects and see if you get warnings.
so you -> so you can.
nit: but I don't really see why the second part is a consequence of the first part.

2024-07-10 14:36 UTC, merged