post: ng v19
Ninja-Squad/ninja-squad.github.com pull request #395
Opened 2024-11-16 08:52 UTC by cexbrayat

2024-11-16 10:44 UTC, jnizet requested changes

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +For each one, you'll get statistics on how many fields have been migrated and how many have been skipped.
fields -> properties

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +For each one, you'll get statistics on how many fields have been migrated and how many have been skipped.
That has already been set before. I'd drop the sentence.

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +
Same for these three above sentences.

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> + useFactory: (service: InitService) => service.init(),
To be fair, inject could already be used, no? So I would rewrite it with inject.

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +so you can now write something like `@if (typeof user === 'object') {` in your templates.
I would rephrase this sentence as

Expressions in the template can now use the `typeof`operator, so you can write things like

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +Its type is `Signal<unknown>`, so you'll have to cast it to the correct type.
I would remove that sentence, because the line of code above makes it clearer (and doesn't really use a cast).

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +to refresh the resources from the network.
I would rephrase the above sentence as 

When the time before the expiration of a cached resource is less than this `refreshAhead` delay, Angular refreshes the resource.

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> + }
Wrong indentation

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +There are a ton of changes in the Server-Side Rendering (SSR) part of Angular,
There are a ton of -> There are tons of

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +When working with SSR, you need to know when the application is stable,
you need -> Angular needs

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +Zone.js usually does this but in a zoneless application,
usually allows knowing this

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +it allows to mark an observable as important for the application stability until a first event is emitted:
it allows marking

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +In v18, `ng build` generated a `browser` folder with `index.html` and `about/index.html` files (with `"prerender": true`).
I'd drop the "(with `"prerender": true`)". We're talking about prerendering, so that's obvious to me.

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +You can also define a `getPrerenderParams` function, to prerender routes with parameters.
The second solution is to define...

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +The server routes configuration doesn't need to define all the routes as you can see,
I'd drop this, and the following example about unknown routes. It goes into too much details.

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +export const serverRoutes: Array<ServerRoute> = [
I would either leave the other two routes there (which, according to the above, are necessary), or just display the new route, without the `export const ...`

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> + }
wrong indentation

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> + path: 'users/**',
Can't we use `users/:id`?

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +Note that `server.ts` is now used during prerendering,
This deserves more than a note. It was a pain in the ass not to be able to use it during development, and a big source of confusion.

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +This feature is going to be really useful to all Sass users,
I would drop this sentence

2024-11-16 10:44 UTC, jnizet commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +This option applies the recommendations from the [Web.dev article](https://web.dev/articles/strict-csp#choose-hash)
from the -> from this ?

2024-11-18 07:11 UTC, cexbrayat commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +You can disable the diagnostic if needed with:
Yes, exactly. On OiA for example, we had a few hundreds of imports to fix.

2024-11-18 07:16 UTC, cexbrayat commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +Component effects now run _during_ change detection and not _after_ it as it was the case before.
I wanted to point out that they run as part of the change detection, at the beginning of it (hence running `detectChanges` in tests triggers them)

2024-11-18 08:14 UTC, cexbrayat commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> + selectedItem = linkedSignal</* source */ Array<ItemModel>, /* value */ ItemModel>({
Otherwise, previousChoice is not properly inferred. So we either need to cast `previous.value` to `itemModel` or add the generic parameters to the linked signal.

2024-11-18 08:36 UTC, cexbrayat commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +(for example to implement a debounce).
FYI a debounce would look like this:
```ts
loader: async params => {
  const abortSignal = params.abortSignal;
  await timeout(400);
  if (abortSignal.aborted) {
    return;
  }
  const response = await fetch(`/users?sort=${request.sort}`);
  // ...
```
But I agree that the abortSignal code should probably always be there.

2024-11-18 09:11 UTC, cexbrayat commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> + useFactory: (service: InitService) => service.init(),
Right. FYI the init function now runs in the injection context, so it can use `inject` directly.

2024-11-18 09:20 UTC, cexbrayat commented on _posts/2024-11-19-what-is-new-angular-19.0.md
> +This feature is going to be really useful to all Sass users,
wait until you see the pile of warnings we get on our projects 😅

2024-11-19 14:54 UTC, merged